-- creates a table and a database
-- the table has a UNIQUE id which is autogenerated(AUTO_INCREMENT) is not null and is a primary key
-- the name cant be null
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states (id INT UNIQUE NOT NULL AUTO_INCREMENT, name VARCHAR(256) NOT NULL, PRIMARY KEY(id));
