-- creates a database and a table
-- the table's id should should be unique, autogenerated, primary key
-- the table's state_id should be a foreing key that references to the id of the state table
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities (id INT NOT NULL UNIQUE AUTO_INCREMENT, state_id INT NOT NULL, 
name VARCHAR(256), PRIMARY KEY(id), FOREIGN KEY(state_id) REFERENCES states(id));
