#!/usr/bin/env bash
#configure the localhost IP from 127.0.0.1 to 127.0.0.2
#also for facebook configured to 8.8.8.8 from 157.240.229.35
#use ping to identify the IP address for both above after copying

cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
